// let data;
// console.log(typeof data);
// let num=50;
// let decimal_no=1.001;
// console.log(typeof num);
// console.log(typeof decimal_no);
// let num1=100;
// let num2=125;
// let addition=num1+num2;
// console.log(addition);
// let substraction=num1-num2;
// console.log(substraction);
// let division=num1/num2;
// console.log(division);
// let multiplication=num1*num2;
// console.log(multiplication);
// let num3=0;let num4=10;
// console.log(num4/num3);
// console.log(`${num3}+${num4}`);
let name="Dibyananda subudhi";
let age=23;
let address="cuttack";
let college="USBM";
let rollnumber=2305274039;
console.log(`My name is :${name},Age :${age},Address :${address} ,college :${college},Rollnumber :${rollnumber}`);
